# Generated by Django 5.1.5 on 2025-01-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.JSONField(default=list)),
                ('albums', models.JSONField(default=list)),
            ],
        ),
    ]
