# Generated by Django 5.1.5 on 2025-02-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_followedartist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowedArtist',
        ),
    ]
